language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install git+https://github.com/jaybaird/python-bloomfilter.git
  - pip install -r test_requirements.txt

script:
  - python -m pytest --verbose --cov=xcrawler tests
  - coveralls