language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install git+https://github.com/jaybaird/python-bloomfilter.git
  - pip install lxml
  - pip install beautifulsoup4
  - pip install requests
  - pip install coverage
  - pip install coveralls

script:
  - python -m pytest --verbose --cov=xcrawler tests
  - coveralls